### ISSUE TITLE
افزودن نمودار

### ISSUE THREAD

**Issue by ohmydevops** [amirshnll/corona#2]
<div dir='rtl'>

اگر موافق هستی من میتونم روی ایجاد نمودار زمان بزارم. نمودار ۳۰ یا ۱۰ روز گذشته که این اعداد بیشتر توی ذهن مخاطب بشینن

</div>

**Comment by ohmydevops** [comment]
یک نمونه کوچیک آماده میکنم که منظورم رو بهتر برسونم و اگر موافق بودی بهترش کنیم و به سایت اضافه کنیم.

**Comment by ghost** [comment]
@ohmydevops امیرحسین جان به پروژه اضافت کردم

**Comment by ohmydevops** [comment]
![image](https://user-images.githubusercontent.com/21690865/128997895-e8e05757-1598-47c7-bacf-be43062e9f52.png)

**Comment by ohmydevops** [comment]
جهت لیبل‌ها رو باید اصلاح کنم

**Comment by ohmydevops** [comment]
> @ohmydevops امیرحسین جان به پروژه اضافت کردم

ممنونم ازت. یک سری تغییرات دارم میدم دونه دونه توی برنچ دیگه‌ای کامیت میکنم که اگر صلاح دیدی اضافه کنیم

**Comment by ghost** [comment]
متشکرم
