### ISSUE TITLE
آمار رسمی در مقابل آمار واقعی نامعلوم

### ISSUE THREAD

**Issue by ohmydevops** [amirshnll/corona#3]
به نظرم خوبه در جایی از سایت اشاره بشه این آمار بر اساس اعلام رسمی جمهوری اسلامی گردآوری میشه و صدالبته با آنچه در واقعیت روی داده متفاوته

**Comment by ghost** [comment]
آخر صفحه میتونیم بزاریم چون من هر کسی که میبینم رعایت نمیکنه این لینک رو بهش میدم تمرکز بالای صفحه رو میگیره همین اعداد هم خیلی ترسناک و ناراحت کنندس

**Comment by ohmydevops** [comment]
درسته. آخرش میشه گذاشت.
من اضافه میکنم توی این برنچ جدید
